services:
  db:
    image: postgres:16
    restart: always
    environment:
      APP_ENV: 'test'
      POSTGRES_CONFIG: '{"host":"localhost","port":"5432","user":"testuser","password":"testpass","database":"testdb"}'
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass   # <--- добавь это!
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: 
