name: Deploy to Cloud Run

on:
  push:
    # Deploy on push to any branch during testing
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: instagram-video-downloader
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set branch name for service
        run: |
          # Extract branch name and make it URL-friendly for service name
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          CLEAN_BRANCH_NAME=$(echo $BRANCH_NAME | tr '/' '-' | tr '_' '-' | tr '[:upper:]' '[:lower:]')
          if [ "$CLEAN_BRANCH_NAME" = "main" ] || [ "$CLEAN_BRANCH_NAME" = "master" ]; then
            # Use the regular service name for main/master
            echo "DEPLOY_SERVICE_NAME=$SERVICE_NAME" >> $GITHUB_ENV
          else
            # Append branch name for other branches
            # Limit to 49 chars to avoid exceeding GCP service name length limits
            SERVICE_PREFIX=$(echo $SERVICE_NAME | cut -c 1-30)
            BRANCH_SUFFIX=$(echo $CLEAN_BRANCH_NAME | cut -c 1-18)
            echo "DEPLOY_SERVICE_NAME=${SERVICE_PREFIX}-${BRANCH_SUFFIX}" >> $GITHUB_ENV
          fi

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and push container
        run: |
          docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }} .
          docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $DEPLOY_SERVICE_NAME \
            --image gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }} \
            --platform managed \
            --region $REGION \
            --memory 512Mi \
            --cpu 1 \
            --timeout 300 \
            --concurrency 80 \
            --update-secrets INSTAGRAM_APP_NAME=INSTAGRAM_APP_NAME:latest,INSTAGRAM_APP_ID=INSTAGRAM_APP_ID:latest,INSTAGRAM_APP_SECRET=INSTAGRAM_APP_SECRET:latest,INSTAGRAM_ACCESS_TOKEN=INSTAGRAM_ACCESS_TOKEN:latest,INSTAGRAM_ACCESS_TOKEN_ARRAY=INSTAGRAM_ACCESS_TOKEN_ARRAY:latest,ALLOWED_SENDER_ID=ALLOWED_SENDER_ID:latest,IG_ID=IG_ID:latest,FIREBASE_CONFIG=FIREBASE_CONFIG:latest,YT_CLOUD_ID=YT_CLOUD_ID:latest,YT_SECRET_ID=YT_SECRET_ID:latest,YT_REDIRECT_URL=YT_REDIRECT_URL:latest,YT_REFRESH_TOKEN=YT_REFRESH_TOKEN:latest \
            --set-env-vars ENABLE_STDERR=true,ENABLE_PROGRESS=true,ENABLE_START=true,ENABLE_DOWNLOAD_VIDEO=true,ENABLE_RUN_SCENARIO_VIDEO=true \
            --allow-unauthenticated
