name: Instagram Video Downloader Cloud Run

on:
  push:
    # Deploy on push to any branch during testing
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: instagram-video-downloader
  REGION: europe-central2
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build docker image
        run: docker build -t $SERVICE_NAME:$GITHUB_SHA .
  
  deploy:
    name: Deploy
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      # Authenticate with Google Cloud
      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      # Setup gcloud CLI/SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Set branch name for service
        run: |
          # Extract branch name and make it URL-friendly for service name
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          CLEAN_BRANCH_NAME=$(echo $BRANCH_NAME | tr '/' '-' | tr '_' '-' | tr '[:upper:]' '[:lower:]')
          if [ "$CLEAN_BRANCH_NAME" = "main" ] || [ "$CLEAN_BRANCH_NAME" = "master" ]; then
            # Use the regular service name for main/master
            echo "DEPLOY_SERVICE_NAME=$SERVICE_NAME" >> $GITHUB_ENV
          else
            # Append branch name for other branches
            # Limit to 49 chars to avoid exceeding GCP service name length limits
            SERVICE_PREFIX=$(echo $SERVICE_NAME | cut -c 1-30)
            BRANCH_SUFFIX=$(echo $CLEAN_BRANCH_NAME | cut -c 1-18)
            echo "DEPLOY_SERVICE_NAME=${SERVICE_PREFIX}-${BRANCH_SUFFIX}" >> $GITHUB_ENV
          fi

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and tag the docker image
        run: docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA .

      - name: Push the image to the Google Container Registry (GCR)
        run: docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $DEPLOY_SERVICE_NAME \
            --image gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
            --platform managed \
            --region $REGION \
            --memory 512Mi \
            --cpu 1 \
            --timeout 300 \
            --concurrency 80 \
            --update-secrets INSTAGRAM_APP_NAME=INSTAGRAM_APP_NAME:latest,INSTAGRAM_APP_ID=INSTAGRAM_APP_ID:latest,INSTAGRAM_APP_SECRET=INSTAGRAM_APP_SECRET:latest,INSTAGRAM_ACCESS_TOKEN=INSTAGRAM_ACCESS_TOKEN:latest,INSTAGRAM_ACCESS_TOKEN_ARRAY=INSTAGRAM_ACCESS_TOKEN_ARRAY:latest,ALLOWED_SENDER_ID=ALLOWED_SENDER_ID:latest,IG_ID=IG_ID:latest,FIREBASE_CONFIG=FIREBASE_CONFIG:latest,YT_CLOUD_ID=YT_CLOUD_ID:latest,YT_SECRET_ID=YT_SECRET_ID:latest,YT_REDIRECT_URL=YT_REDIRECT_URL:latest,YT_REFRESH_TOKEN=YT_REFRESH_TOKEN:latest \
            --set-env-vars ENABLE_STDERR=true,ENABLE_PROGRESS=true,ENABLE_START=true,ENABLE_DOWNLOAD_VIDEO=true,ENABLE_RUN_SCENARIO_VIDEO=true \
            --allow-unauthenticated
